package com.zook.devtech.gregtech.recipes.constants;

import com.zook.devtech.gregtech.recipes.IDTTextureArea;
import com.zook.devtech.gregtech.recipes.impl.MCTextureArea;
import crafttweaker.annotations.ZenRegister;
import gregtech.api.gui.GuiTextures;
import stanhebben.zenscript.annotations.ZenClass;
import stanhebben.zenscript.annotations.ZenProperty;

@ZenClass("mods.devtech.GUITextures")
@ZenRegister
public class ConstantSlotOverlays {
    @ZenProperty public static final IDTTextureArea TOOL_SLOT_OVERLAY = new MCTextureArea(GuiTextures.TOOL_SLOT_OVERLAY);
    @ZenProperty public static final IDTTextureArea ARROW_INPUT_OVERLAY = new MCTextureArea(GuiTextures.ARROW_INPUT_OVERLAY);
    @ZenProperty public static final IDTTextureArea ARROW_OUTPUT_OVERLAY = new MCTextureArea(GuiTextures.ARROW_OUTPUT_OVERLAY);
    @ZenProperty public static final IDTTextureArea CHARGER_OVERLAY = new MCTextureArea(GuiTextures.CHARGER_OVERLAY);
    @ZenProperty public static final IDTTextureArea INT_CIRCUIT_OVERLAY = new MCTextureArea(GuiTextures.INT_CIRCUIT_OVERLAY);
    @ZenProperty public static final IDTTextureArea TURBINE_OVERLAY = new MCTextureArea(GuiTextures.TURBINE_OVERLAY);
    @ZenProperty public static final IDTTextureArea FURNACE_OVERLAY = new MCTextureArea(GuiTextures.FURNACE_OVERLAY);
    @ZenProperty public static final IDTTextureArea COMPRESSOR_OVERLAY = new MCTextureArea(GuiTextures.COMPRESSOR_OVERLAY);
    @ZenProperty public static final IDTTextureArea EXTRACTOR_OVERLAY = new MCTextureArea(GuiTextures.EXTRACTOR_OVERLAY);
    @ZenProperty public static final IDTTextureArea CRUSHED_ORE_OVERLAY = new MCTextureArea(GuiTextures.CRUSHED_ORE_OVERLAY);
    @ZenProperty public static final IDTTextureArea DUST_OVERLAY = new MCTextureArea(GuiTextures.DUST_OVERLAY);
    @ZenProperty public static final IDTTextureArea INGOT_OVERLAY = new MCTextureArea(GuiTextures.INGOT_OVERLAY);
    @ZenProperty public static final IDTTextureArea CIRCUIT_OVERLAY = new MCTextureArea(GuiTextures.CIRCUIT_OVERLAY);
    @ZenProperty public static final IDTTextureArea BATTERY_OVERLAY = new MCTextureArea(GuiTextures.BATTERY_OVERLAY);
    @ZenProperty public static final IDTTextureArea PRESS_OVERLAY_1 = new MCTextureArea(GuiTextures.PRESS_OVERLAY_1);
    @ZenProperty public static final IDTTextureArea PRESS_OVERLAY_2 = new MCTextureArea(GuiTextures.PRESS_OVERLAY_2);
    @ZenProperty public static final IDTTextureArea PRESS_OVERLAY_3 = new MCTextureArea(GuiTextures.PRESS_OVERLAY_3);
    @ZenProperty public static final IDTTextureArea DARK_CANISTER_OVERLAY = new MCTextureArea(GuiTextures.DARK_CANISTER_OVERLAY);
    @ZenProperty public static final IDTTextureArea CANISTER_OVERLAY = new MCTextureArea(GuiTextures.CANISTER_OVERLAY);
    @ZenProperty public static final IDTTextureArea LENS_OVERLAY = new MCTextureArea(GuiTextures.LENS_OVERLAY);
    @ZenProperty public static final IDTTextureArea CRYSTAL_OVERLAY = new MCTextureArea(GuiTextures.CRYSTAL_OVERLAY);
    @ZenProperty public static final IDTTextureArea BREWER_OVERLAY = new MCTextureArea(GuiTextures.BREWER_OVERLAY);
    @ZenProperty public static final IDTTextureArea SOLIDIFIER_OVERLAY = new MCTextureArea(GuiTextures.SOLIDIFIER_OVERLAY);
    @ZenProperty public static final IDTTextureArea MOLECULAR_OVERLAY_1 = new MCTextureArea(GuiTextures.MOLECULAR_OVERLAY_1);
    @ZenProperty public static final IDTTextureArea MOLECULAR_OVERLAY_2 = new MCTextureArea(GuiTextures.MOLECULAR_OVERLAY_2);
    @ZenProperty public static final IDTTextureArea MOLECULAR_OVERLAY_3 = new MCTextureArea(GuiTextures.MOLECULAR_OVERLAY_3);
    @ZenProperty public static final IDTTextureArea VIAL_OVERLAY_1 = new MCTextureArea(GuiTextures.VIAL_OVERLAY_1);
    @ZenProperty public static final IDTTextureArea VIAL_OVERLAY_2 = new MCTextureArea(GuiTextures.VIAL_OVERLAY_2);
    @ZenProperty public static final IDTTextureArea WIREMILL_OVERLAY = new MCTextureArea(GuiTextures.WIREMILL_OVERLAY);
    @ZenProperty public static final IDTTextureArea BENDER_OVERLAY = new MCTextureArea(GuiTextures.BENDER_OVERLAY);
    @ZenProperty public static final IDTTextureArea CANNER_OVERLAY = new MCTextureArea(GuiTextures.CANNER_OVERLAY);
    @ZenProperty public static final IDTTextureArea PIPE_OVERLAY_1 = new MCTextureArea(GuiTextures.PIPE_OVERLAY_1);
    @ZenProperty public static final IDTTextureArea PIPE_OVERLAY_2 = new MCTextureArea(GuiTextures.PIPE_OVERLAY_2);
    @ZenProperty public static final IDTTextureArea BOX_OVERLAY = new MCTextureArea(GuiTextures.BOX_OVERLAY);
    @ZenProperty public static final IDTTextureArea BOXED_OVERLAY = new MCTextureArea(GuiTextures.BOXED_OVERLAY);
    @ZenProperty public static final IDTTextureArea CUTTER_OVERLAY = new MCTextureArea(GuiTextures.CUTTER_OVERLAY);
    @ZenProperty public static final IDTTextureArea MOLD_OVERLAY = new MCTextureArea(GuiTextures.MOLD_OVERLAY);
    @ZenProperty public static final IDTTextureArea HAMMER_OVERLAY = new MCTextureArea(GuiTextures.HAMMER_OVERLAY);
    @ZenProperty public static final IDTTextureArea PAPER_OVERLAY = new MCTextureArea(GuiTextures.PAPER_OVERLAY);
    @ZenProperty public static final IDTTextureArea PRINTED_PAPER_OVERLAY = new MCTextureArea(GuiTextures.PRINTED_PAPER_OVERLAY);
    @ZenProperty public static final IDTTextureArea IN_SLOT_OVERLAY = new MCTextureArea(GuiTextures.IN_SLOT_OVERLAY);
    @ZenProperty public static final IDTTextureArea OUT_SLOT_OVERLAY = new MCTextureArea(GuiTextures.OUT_SLOT_OVERLAY);
    @ZenProperty public static final IDTTextureArea FILTER_SLOT_OVERLAY = new MCTextureArea(GuiTextures.FILTER_SLOT_OVERLAY);
    @ZenProperty public static final IDTTextureArea STRING_SLOT_OVERLAY = new MCTextureArea(GuiTextures.STRING_SLOT_OVERLAY);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_UNLOCK = new MCTextureArea(GuiTextures.PROGRESS_BAR_UNLOCK);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_ARROW = new MCTextureArea(GuiTextures.PROGRESS_BAR_ARROW);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_ARROW_MULTIPLE = new MCTextureArea(GuiTextures.PROGRESS_BAR_ARROW_MULTIPLE);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_BATH = new MCTextureArea(GuiTextures.PROGRESS_BAR_BATH);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_BENDING = new MCTextureArea(GuiTextures.PROGRESS_BAR_BENDING);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_CANNER = new MCTextureArea(GuiTextures.PROGRESS_BAR_CANNER);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_CIRCUIT = new MCTextureArea(GuiTextures.PROGRESS_BAR_CIRCUIT);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_COMPRESS = new MCTextureArea(GuiTextures.PROGRESS_BAR_COMPRESS);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_EXTRACT = new MCTextureArea(GuiTextures.PROGRESS_BAR_EXTRACT);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_EXTRUDER = new MCTextureArea(GuiTextures.PROGRESS_BAR_EXTRUDER);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_HAMMER = new MCTextureArea(GuiTextures.PROGRESS_BAR_HAMMER);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_LATHE = new MCTextureArea(GuiTextures.PROGRESS_BAR_LATHE);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_MACERATE = new MCTextureArea(GuiTextures.PROGRESS_BAR_MACERATE);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_MAGNET = new MCTextureArea(GuiTextures.PROGRESS_BAR_MAGNET);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_RECYCLER = new MCTextureArea(GuiTextures.PROGRESS_BAR_RECYCLER);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_SIFT = new MCTextureArea(GuiTextures.PROGRESS_BAR_SIFT);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_SLICE = new MCTextureArea(GuiTextures.PROGRESS_BAR_SLICE);
    @ZenProperty public static final IDTTextureArea PROGRESS_BAR_WIREMILL = new MCTextureArea(GuiTextures.PROGRESS_BAR_WIREMILL);
}
